name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/tests.yml
    with:
      build: true

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: docker build .
